name: Build & Release
on:
  workflow_dispatch:
  push:
    branches: [main]
permissions:
  contents: write
  packages: write
jobs:
  release:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Get all history for proper versioning
      
      - name: Install pnpm
        run: npm install -g pnpm
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      
      - name: Install dependencies
        run: pnpm install
      
      - name: Get version from package.json
        id: get_version
        shell: bash
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=v$VERSION"
          echo "VERSION=v$VERSION" >> $GITHUB_ENV
      
      - name: Create or force push version tag
        shell: bash
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag -f "$VERSION"
          git push -f https://${{ secrets.GH_PAT }}@github.com/VishalKaleria/social-saver.git "$VERSION"
      
      - name: Build application
        run: pnpm run build
      
      - name: Publish Release
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
          EP_GH_IGNORE_TIME: true
          ELECTRON_BUILDER_ALLOW_SAME_VERSION: true
        run: |
          pnpm exec electron-builder --publish always
